apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: roboshop
  labels:
    component: frontend
    project: roboshop
    tier: frontend
spec:
  replicas: 1
  selector:
    #these lables are used to select pods
    matchLabels:
      component: frontend
      project: roboshop
      tier: frontend
      #pod definition
  template:
    metadata:
      labels:
        component: frontend
        project: roboshop
        tier: frontend
    spec:
      containers:
        - name: frontend
          image: tonyduck/frontend:v1
          imagePullPolicy: Always
          # envFrom:
          #   - configMapRef:
          #       name: frontend
          ports:
            - name: liveness-port
              containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: liveness-port
            failureThreshold: 1
            periodSeconds: 45
            # Override pod-level terminationGracePeriodSeconds #
            # terminationGracePeriodSeconds: 45
          livenessProbe:
            httpGet:
              path: /
              port: liveness-port
            failureThreshold: 1
            periodSeconds: 45
            # Override pod-level terminationGracePeriodSeconds #
            terminationGracePeriodSeconds: 45
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: roboshop
spec:
  type: LoadBalancer
  selector:
    component: frontend
    project: roboshop
    tier: frontend
  ports:
    - protocol: TCP
      port: 80 #service port - clusterIPport
      targetPort: 80
      nodePort: 30001
