apiVersion: v1
kind: ConfigMap
metadata:
  name: payment
  namespace: roboshop
data:
  CART_HOST: "cart"
  CART_PORT: "8080"
  USER_HOST: "user"
  USER_PORT: "8080"
  AMQP_HOST: "rabbitmq"
  AMQP_USER: "roboshop"
  AMQP_PASS: "roboshop123"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  namespace: roboshop
  labels:
    component: payment
    project: roboshop
    tier: backend
spec:
  replicas: 1
  selector:
    #these lables are used to sleect pods
    matchLabels:
      component: payment
      project: roboshop
      tier: backend
      #pod definition
  template:
    metadata:
      labels:
        component: payment
        project: roboshop
        tier: backend
    spec:
      containers:
        - name: payment
          image: tonyduck/payment:v1
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: payment
          ports:
            - name: liveness-port
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: liveness-port
            failureThreshold: 1
            periodSeconds: 45
            # Override pod-level terminationGracePeriodSeconds #
            # terminationGracePeriodSeconds: 45
          livenessProbe:
            httpGet:
              path: /health
              port: liveness-port
            failureThreshold: 1
            periodSeconds: 45
            # Override pod-level terminationGracePeriodSeconds #
            terminationGracePeriodSeconds: 45
---
apiVersion: v1
kind: Service
metadata:
  name: payment
  namespace: roboshop
spec:
  selector:
    component: payment
    project: roboshop
    tier: backend
  ports:
    - protocol: TCP
      port: 8080 #service port - clusterIPport
      targetPort: 8080
