apiVersion: v1
kind: ConfigMap
metadata:
  name: cart
  namespace: roboshop
data:
  # REDIS_HOST: "redis"
  # CATALOGUE_HOST: "catalogue"
  # CATALOGUE_PORT: "8080"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart
  namespace: roboshop
  labels:
    component: cart
    project: roboshop
    tier: backend
spec:
  replicas: 1
  selector:
    #these lables are used to sleect pods
    matchLabels:
      component: cart
      project: roboshop
      tier: backend
      #pod definition
  template:
    metadata:
      labels:
        component: cart
        project: roboshop
        tier: backend
    spec:
      containers:
        - name: cart
          image: tonyduck/cart:v1
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: cart
          ports:
            - name: liveness-port
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: liveness-port
            failureThreshold: 1
            periodSeconds: 45
            # Override pod-level terminationGracePeriodSeconds #
            # terminationGracePeriodSeconds: 45
          livenessProbe:
            httpGet:
              path: /health
              port: liveness-port
            failureThreshold: 1
            periodSeconds: 45
            # Override pod-level terminationGracePeriodSeconds #
            terminationGracePeriodSeconds: 45
---
apiVersion: v1
kind: Service
metadata:
  name: cart
  namespace: roboshop
spec:
  selector:
    component: cart
    project: roboshop
    tier: backend
  ports:
    - protocol: TCP
      port: 8080 #service port - clusterIPport
      targetPort: 8080
