apiVersion: v1
kind: ConfigMap
metadata:
  name: shipping
  namespace: roboshop
data:
  CART_ENDPOINT: "cart:8080"
  DB_HOST: "mysql"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping
  namespace: roboshop
  labels:
    component: shipping
    project: roboshop
    tier: backend
spec:
  replicas: 1
  selector:
    #these lables are used to sleect pods
    matchLabels:
      component: shipping
      project: roboshop
      tier: backend
      #pod definition
  template:
    metadata:
      labels:
        component: shipping
        project: roboshop
        tier: backend
    spec:
      containers:
        - name: shipping
          image: tonyduck/shipping:v1
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: shipping
          ports:
            - name: liveness-port
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: liveness-port
            failureThreshold: 1
            periodSeconds: 45
            # Override pod-level terminationGracePeriodSeconds #
            # terminationGracePeriodSeconds: 45
          livenessProbe:
            httpGet:
              path: /health
              port: liveness-port
            failureThreshold: 1
            periodSeconds: 45
            # Override pod-level terminationGracePeriodSeconds #
            terminationGracePeriodSeconds: 45
---
apiVersion: v1
kind: Service
metadata:
  name: shipping
  namespace: roboshop
spec:
  selector:
    component: shipping
    project: roboshop
    tier: backend
  ports:
    - protocol: TCP
      port: 8080 #service port - clusterIPport
      targetPort: 8080
