apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: roboshop
  labels:
    component: rabbitmq
    project: roboshop
    tier: db
spec:
  replicas: 1
  selector:
    #these lables are used to sleect pods
    matchLabels:
      component: rabbitmq
      project: roboshop
      tier: db
      #pod definition
  template:
    metadata:
      labels:
        component: rabbitmq
        project: roboshop
        tier: db
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3
          imagePullPolicy: Always
          readinessProbe:
            tcpSocket:
              port: 5672
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 5672
            initialDelaySeconds: 15
            periodSeconds: 10            
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: roboshop
spec:
  selector:
    component: rabbitmq
    project: roboshop
    tier: db
  ports:
    - protocol: TCP
      port: 5672 #service port - clusterIPport
      targetPort: 5672