apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: roboshop
  labels:
    component: mongodb
    project: roboshop
    tier: db
spec:
  replicas: 1
  selector:
    #these lables are used to sleect pods
    matchLabels:
      component: mongodb
      project: roboshop
      tier: db
      #pod definition
  template:
    metadata:
      labels:
        component: mongodb
        project: roboshop
        tier: db
    spec:
      containers:
        - name: mongodb
          image: tonyduck/mongodb:v1
          imagePullPolicy: Always
          readinessProbe:
            tcpSocket:
              port: 27017
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 27017
            initialDelaySeconds: 15
            periodSeconds: 10            
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: roboshop
spec:
  selector:
    component: mongodb
    project: roboshop
    tier: db
  ports:
    - protocol: TCP
      port: 27017 #service port - clusterIPport
      targetPort: 27017