apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql
  namespace: roboshop
data:
  my.cnf: |
    [mysqld]
    innodb_redo_log_capacity = 2G

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: roboshop
  labels:
    component: mysql
    project: roboshop
    tier: db
spec:
  replicas: 1
  selector:
    #these lables are used to sleect pods
    matchLabels:
      component: mysql
      project: roboshop
      tier: db
      #pod definition
  template:
    metadata:
      labels:
        component: mysql
        project: roboshop
        tier: db
    spec:
      containers:
        - name: mysql
          image: tonyduck/mysql:v1
          imagePullPolicy: Always
          readinessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 25
            periodSeconds: 10
          volumeMounts:
          - name: mysql-config
            mountPath: /etc/mysql/conf.d/my.cnf
            subPath: my.cnf  
    volumes:
    - name: mysql-config
      configMap:
        name: mysql
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: roboshop
spec:
  selector:
    component: mysql
    project: roboshop
    tier: db
  ports:
    - protocol: TCP
      port: 3306 #service port - clusterIPport
      targetPort: 3306
