apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql
  namespace: roboshop
data:
  my.cnf: |
    [mysqld]
    innodb_redo_log_capacity = 2G

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: roboshop
  labels:
    component: mysql
    project: roboshop
    tier: db
spec:
  replicas: 1
  selector:
    #these lables are used to sleect pods
    matchLabels:
      component: mysql
      project: roboshop
      tier: db
      #pod definition
  template:
    metadata:
      labels:
        component: mysql
        project: roboshop
        tier: db
    spec:
      serviceAccount:  secret-mysql-reader
      initContainers:
      - name: init-fetch-secret
        image: amazon/aws-cli
        command: 
        - sh
        - -c
        - |
           aws secretsmanager get-secret-value --secret-id /roboshop/dev/mysql_password --query 'SecretString' --output text | jq -r '.["mysql-password"]' > /tmp/mysql-root-password.txt
        volumeMounts:
        - name: mysql-secret
          mountPath: /tmp



      containers:
        - name: mysql
          image: tonyduck/mysql:v2
          imagePullPolicy: Always
          readinessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 25
            periodSeconds: 10
          volumeMounts:
            - name: mysql-config
              mountPath: /etc/mysql/conf.d/my.cnf
              subPath: my.cnf
          volumeMounts:
          - name: mysql-secret
            mountPath: /tmp              

      volumes:
        - name: mysql-config
          configMap:
            name: mysql
        - name: mysql-secret
          emptyDir: {}           
