apiVersion: v1
kind: ConfigMap
metadata:
  name: user
  namespace: roboshop
data:
  MONGO: "true"
  REDIS_URL: "redis://redis:6379"
  MONGO_URL: "mongodb://mongodb:27017/users"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  namespace: roboshop
  labels:
    component: user
    project: roboshop
    tier: backend
spec:
  replicas: 1
  selector:
    #these lables are used to sleect pods
    matchLabels:
      component: user
      project: roboshop
      tier: backend
      #pod definition
  template:
    metadata:
      labels:
        component: user
        project: roboshop
        tier: backend
    spec:
      containers:
        - name: user
          image: tonyduck/user:v1
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: user
          ports:
            - name: liveness-port
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: liveness-port
            failureThreshold: 1
            periodSeconds: 45
            # Override pod-level terminationGracePeriodSeconds #
            # terminationGracePeriodSeconds: 45
          livenessProbe:
            httpGet:
              path: /health
              port: liveness-port
            failureThreshold: 1
            periodSeconds: 45
            # Override pod-level terminationGracePeriodSeconds #
            terminationGracePeriodSeconds: 45
---
apiVersion: v1
kind: Service
metadata:
  name: user
  namespace: roboshop
spec:
  selector:
    component: user
    project: roboshop
    tier: backend
  ports:
    - protocol: TCP
      port: 8080 #service port - clusterIPport
      targetPort: 8080
